# Generated by Django 6.0.3 on 2026-03-26 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=100)),
                ('fuel_bays', models.IntegerField()),
                ('finished_date', models.DateTimeField(default=datetime.datetime(2026, 3, 26, 7, 28, 13, 936408, tzinfo=datetime.timezone.utc))),
                ('pilot', models.CharField(choices=[('RK', 'Rocky'), ('RG', 'Grace')], max_length=100)),
                ('image', models.ImageField(upload_to='crafts/')),
            ],
        ),
    ]
