# Generated by Django 6.0.3 on 2026-03-26 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hail_mary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacecraft',
            name='name',
            field=models.CharField(default='Craft', max_length=64),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='finished_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 7, 43, 36, 252213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='image',
            field=models.ImageField(upload_to='hail_mary/spacecrafts'),
        ),
    ]
