# Generated by Django 6.0.3 on 2026-03-26 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hail_mary', '0002_spacecraft_name_alter_spacecraft_finished_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecraft',
            name='finished_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 8, 18, 18, 61359, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
