# Generated by Django 6.0.3 on 2026-03-26 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hail_mary', '0003_alter_spacecraft_finished_date_alter_spacecraft_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecraft',
            name='finished_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 8, 42, 10, 803095, tzinfo=datetime.timezone.utc)),
        ),
    ]
