# Generated by Django 6.0.3 on 2026-03-26 10:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hail_mary', '0004_alter_spacecraft_finished_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecraft',
            name='finished_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 10, 41, 22, 319216, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('space_craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='hail_mary.spacecraft')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_system', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('time_for_trip', models.FloatField()),
                ('space_craft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='hail_mary.spacecraft')),
            ],
        ),
        migrations.CreateModel(
            name='Engineers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('specification', models.CharField(max_length=100)),
                ('space_crafts', models.ManyToManyField(related_name='engineers', to='hail_mary.spacecraft')),
            ],
        ),
    ]
